<Project Sdk="Microsoft.NET.Sdk">

  <ItemGroup>
    <ProjectReference Include="..\SiAman.Domain\SiAman.Domain.csproj" />
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="BCrypt.Net-Next" Version="4.2.0" />
    <PackageReference Include="FluentValidation" Version="12.1.1" />
    <PackageReference Include="Google.Apis.Auth" Version="1.74.0" />
    <PackageReference Include="MediatR" Version="14.1.0" />
    <PackageReference Include="MediatR.Extensions.Microsoft.DependencyInjection" Version="11.1.0" />
    <PackageReference Include="Microsoft.AspNetCore.Http.Abstractions" Version="2.3.9" />
    <PackageReference Include="Microsoft.EntityFrameworkCore" Version="8.0.0" />
    <PackageReference Include="Microsoft.Extensions.Configuration" Version="10.0.7" />
  </ItemGroup>

  <ItemGroup>
    <Folder Include="Common\Behaviours\" />
    <Folder Include="Common\Exceptions\" />
    <Folder Include="Common\Models\" />
    <Folder Include="Features\Auth\Commands\LoginManualWithEmail\" />
    <Folder Include="Features\Auth\Commands\LoginWithGoogle\" />
    <Folder Include="Features\Auth\Commands\RefreshToken\" />
    <Folder Include="Features\Auth\DTOs\" />
    <Folder Include="Features\Auth\Queries\" />
    <Folder Include="Features\Auth\Queries\GetCurrentUser\" />
    <Folder Include="Users\" />
    <Folder Include="Users\Command\" />
    <Folder Include="Users\Command\Login\" />
    <Folder Include="Users\Handler\" />
  </ItemGroup>

  <PropertyGroup>
    <TargetFramework>net8.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
  </PropertyGroup>

</Project>
