/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as WargaRouteImport } from './routes/warga'
import { Route as AdminRouteImport } from './routes/admin'
import { Route as IndexRouteImport } from './routes/index'
import { Route as WargaIndexRouteImport } from './routes/warga/index'
import { Route as AdminIndexRouteImport } from './routes/admin/index'
import { Route as WargaSosRouteImport } from './routes/warga/sos'
import { Route as WargaReportSafetyRouteImport } from './routes/warga/report-safety'
import { Route as AdminReportsRouteImport } from './routes/admin/reports'

const WargaRoute = WargaRouteImport.update({
  id: '/warga',
  path: '/warga',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminRoute = AdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const WargaIndexRoute = WargaIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => WargaRoute,
} as any)
const AdminIndexRoute = AdminIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AdminRoute,
} as any)
const WargaSosRoute = WargaSosRouteImport.update({
  id: '/sos',
  path: '/sos',
  getParentRoute: () => WargaRoute,
} as any)
const WargaReportSafetyRoute = WargaReportSafetyRouteImport.update({
  id: '/report-safety',
  path: '/report-safety',
  getParentRoute: () => WargaRoute,
} as any)
const AdminReportsRoute = AdminReportsRouteImport.update({
  id: '/reports',
  path: '/reports',
  getParentRoute: () => AdminRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/admin': typeof AdminRouteWithChildren
  '/warga': typeof WargaRouteWithChildren
  '/admin/reports': typeof AdminReportsRoute
  '/warga/report-safety': typeof WargaReportSafetyRoute
  '/warga/sos': typeof WargaSosRoute
  '/admin/': typeof AdminIndexRoute
  '/warga/': typeof WargaIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/admin/reports': typeof AdminReportsRoute
  '/warga/report-safety': typeof WargaReportSafetyRoute
  '/warga/sos': typeof WargaSosRoute
  '/admin': typeof AdminIndexRoute
  '/warga': typeof WargaIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/admin': typeof AdminRouteWithChildren
  '/warga': typeof WargaRouteWithChildren
  '/admin/reports': typeof AdminReportsRoute
  '/warga/report-safety': typeof WargaReportSafetyRoute
  '/warga/sos': typeof WargaSosRoute
  '/admin/': typeof AdminIndexRoute
  '/warga/': typeof WargaIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/admin'
    | '/warga'
    | '/admin/reports'
    | '/warga/report-safety'
    | '/warga/sos'
    | '/admin/'
    | '/warga/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/admin/reports'
    | '/warga/report-safety'
    | '/warga/sos'
    | '/admin'
    | '/warga'
  id:
    | '__root__'
    | '/'
    | '/admin'
    | '/warga'
    | '/admin/reports'
    | '/warga/report-safety'
    | '/warga/sos'
    | '/admin/'
    | '/warga/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AdminRoute: typeof AdminRouteWithChildren
  WargaRoute: typeof WargaRouteWithChildren
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/warga': {
      id: '/warga'
      path: '/warga'
      fullPath: '/warga'
      preLoaderRoute: typeof WargaRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin': {
      id: '/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AdminRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/warga/': {
      id: '/warga/'
      path: '/'
      fullPath: '/warga/'
      preLoaderRoute: typeof WargaIndexRouteImport
      parentRoute: typeof WargaRoute
    }
    '/admin/': {
      id: '/admin/'
      path: '/'
      fullPath: '/admin/'
      preLoaderRoute: typeof AdminIndexRouteImport
      parentRoute: typeof AdminRoute
    }
    '/warga/sos': {
      id: '/warga/sos'
      path: '/sos'
      fullPath: '/warga/sos'
      preLoaderRoute: typeof WargaSosRouteImport
      parentRoute: typeof WargaRoute
    }
    '/warga/report-safety': {
      id: '/warga/report-safety'
      path: '/report-safety'
      fullPath: '/warga/report-safety'
      preLoaderRoute: typeof WargaReportSafetyRouteImport
      parentRoute: typeof WargaRoute
    }
    '/admin/reports': {
      id: '/admin/reports'
      path: '/reports'
      fullPath: '/admin/reports'
      preLoaderRoute: typeof AdminReportsRouteImport
      parentRoute: typeof AdminRoute
    }
  }
}

interface AdminRouteChildren {
  AdminReportsRoute: typeof AdminReportsRoute
  AdminIndexRoute: typeof AdminIndexRoute
}

const AdminRouteChildren: AdminRouteChildren = {
  AdminReportsRoute: AdminReportsRoute,
  AdminIndexRoute: AdminIndexRoute,
}

const AdminRouteWithChildren = AdminRoute._addFileChildren(AdminRouteChildren)

interface WargaRouteChildren {
  WargaReportSafetyRoute: typeof WargaReportSafetyRoute
  WargaSosRoute: typeof WargaSosRoute
  WargaIndexRoute: typeof WargaIndexRoute
}

const WargaRouteChildren: WargaRouteChildren = {
  WargaReportSafetyRoute: WargaReportSafetyRoute,
  WargaSosRoute: WargaSosRoute,
  WargaIndexRoute: WargaIndexRoute,
}

const WargaRouteWithChildren = WargaRoute._addFileChildren(WargaRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AdminRoute: AdminRouteWithChildren,
  WargaRoute: WargaRouteWithChildren,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
